atlassian/infrastructure

CHANGELOG.md
src/main/kotlin/com/atlassian/performance/tools/infrastructure/api/virtualusers/MulticastVirtualUsers.kt
src/test/kotlin/com/atlassian/performance/tools/infrastructure/ChromedriverInstallerIT.kt
src/test/resources/log4j2.xml

The `com.atlassian.performance.tools.infrastructure.api.virtualusers.MulticastVirtualUsersTest` stdout shows the difference.
Before:
```
2019-04-11T12:01:38,072Z DEBUG multicast-virtual-users-apply load-thread-3 [apply load com.atlassian.performance.tools.infrastructure.api.virtualusers.SingleUseVirtualUsers@7856b18c] [com.atlassian.performance.tools.jvmtasks.api.TaskTimer] The task took PT0.001S
2019-04-11T12:01:38,072Z DEBUG multicast-virtual-users-apply load-thread-1 [apply load com.atlassian.performance.tools.infrastructure.api.virtualusers.SingleUseVirtualUsers@6c2fabed] [com.atlassian.performance.tools.jvmtasks.api.TaskTimer] The task took PT0.001S
2019-04-11T12:01:38,072Z DEBUG multicast-virtual-users-apply load-thread-0 [apply load …
```

JPERF-453: Quiet down the multicast VU log context

---

CHANGELOG.md

https://travis-ci.com/atlassian/infrastructure/builds/109287071

Mark release 4.12.2

---

CHANGELOG.md

https://packages.atlassian.com/maven-public/com/atlassian/performance/tools/infrastructure/4.12.3/

Mark 4.12.3 release

---

CHANGELOG.md
src/main/kotlin/com/atlassian/performance/tools/infrastructure/api/dataset/FileArchiver.kt
src/main/kotlin/com/atlassian/performance/tools/infrastructure/dataset/HttpDatasetPackage.kt

The issue was introduced while working on JPERF-496.

JPERF-504: Fix dataset unzipping performance.

---

CHANGELOG.md

https://packages.atlassian.com/maven-public/com/atlassian/performance/tools/infrastructure/4.13.0/

Mark 4.13.0 release

---

CHANGELOG.md
src/main/kotlin/com/atlassian/performance/tools/infrastructure/api/profiler/WallClockProfiler.kt

I'm using the implementation internally, but have no integration tests.

JPERF-531: Add support for wall-clock profiler

---

.travis.yml

See https://github.com/gradle/gradle/pull/10381 for a similar workaround.

JPERF-590: Work around "plugin was not found" problem

---

CHANGELOG.md

Proof: https://packages.atlassian.com/maven-public/com/atlassian/performance/tools/infrastructure/4.14.4/

Mark 4.14.4 release

---

CHANGELOG.md

Artifacts: https://packages.atlassian.com/maven-public/com/atlassian/performance/tools/infrastructure/4.14.5/

Mark 4.14.5 release

---

.circleci/config.yml

Gain more cross-module consistency as a bonus.

Test on CircleCI for speed

---

CHANGELOG.md

JPERF-625: Fix changelog

---

CHANGELOG.md

Artifacts: https://packages.atlassian.com/maven-public/com/atlassian/performance/tools/infrastructure/4.16.1/

Mark 4.16.1 release

---

CHANGELOG.md

Artifacts: https://packages.atlassian.com/maven-central/com/atlassian/performance/tools/infrastructure/4.17.2/

Mark 4.17.2 release

---

CHANGELOG.md
src/main/kotlin/com/atlassian/performance/tools/infrastructure/api/database/MySqlDatabase.kt

Bumped version of MySQL to 5.7.32
Updated CHANGELOG.md

JPERF-671 Bump MySQL to 5.7

---

CHANGELOG.md

Artifacts: https://packages.atlassian.com/maven-central/com/atlassian/performance/tools/infrastructure/4.17.5/

Mark 4.17.5 release

---

CHANGELOG.md

https://packages.atlassian.com/maven-central/com/atlassian/performance/tools/infrastructure/4.20.0/

Mark 4.20.0

---

CHANGELOG.md
src/main/kotlin/com/atlassian/performance/tools/infrastructure/api/database/MySqlDatabase.kt
src/main/kotlin/com/atlassian/performance/tools/infrastructure/api/splunk/AtlassianSplunkForwarder.kt
src/main/kotlin/com/atlassian/performance/tools/infrastructure/api/splunk/UniversalSplunkForwarder.kt

https://packages.atlassian.com/maven-central/com/atlassian/performance/tools/infrastructure/4.21.0/

Mark 4.21.0 release

---

CHANGELOG.md
src/main/kotlin/com/atlassian/performance/tools/infrastructure/PublicAtlassianProduct.kt
src/main/kotlin/com/atlassian/performance/tools/infrastructure/api/distribution/PublicJiraServiceDeskDistribution.kt
src/main/kotlin/com/atlassian/performance/tools/infrastructure/api/distribution/PublicJiraSoftwareDistribution.kt
src/main/kotlin/com/atlassian/performance/tools/infrastructure/api/distribution/TarGzDistribution.kt
src/test/kotlin/com/atlassian/performance/tools/infrastructure/api/distribution/PublicJiraServiceDeskDistributionIT.kt
src/test/kotlin/com/atlassian/performance/tools/infrastructure/api/distribution/PublicJiraSoftwareDistributionsIT.kt

JPERF-896: install RC distros

---

CHANGELOG.md

https://packages.atlassian.com/maven-central/com/atlassian/performance/tools/infrastructure/4.22.3/

Mark 4.22.3 release

---

.github/workflows/ci.yml
build.gradle.kts

Simplify the CI logic, get Gradle Scans.
Inspired by aws-infrastructure CI.

Use Gradle GHA action

---

CHANGELOG.md

https://packages.atlassian.com/maven-central/com/atlassian/performance/tools/infrastructure/4.22.5/

Mark 4.22.5 release

---

src/test/kotlin/com/atlassian/performance/tools/infrastructure/api/database/MySqlDatabaseIT.kt

Mounting Docker Engine socket didn't work locally on MacOS. Changed to only set privilaged mode.

JPERF-996: Harvest MySqlDatabaseIT from #124

---

CHANGELOG.md

https://packages.atlassian.com/maven-central/com/atlassian/performance/tools/infrastructure/4.24.0/

Mark 4.24.0

---

CHANGELOG.md

https://packages.atlassian.com/maven-central/com/atlassian/performance/tools/infrastructure/4.24.1/

Mark 4.24.1 release

---

CHANGELOG.md

Mark 4.25.0

---

CHANGELOG.md

https://packages.atlassian.com/maven-central/com/atlassian/performance/tools/infrastructure/4.28.1/

Mark 4.28.1
