atlassian/infrastructure

CHANGELOG.md, src/main/kotlin/com/atlassian/performance/tools/infrastructure/api/jira/JiraJvmArgs.kt, src/main/kotlin/com/atlassian/performance/tools/infrastructure/api/jira/JiraNodeConfig.kt, src/main/kotlin/com/atlassian/performance/tools/infrastructure/api/jira/SetenvSh.kt, src/main/kotlin/com/atlassian/performance/tools/infrastructure/api/jvm/AdoptOpenJDK.kt, src/main/kotlin/com/atlassian/performance/tools/infrastructure/api/jvm/AdoptOpenJDK11.kt, src/main/kotlin/com/atlassian/performance/tools/infrastructure/api/jvm/OpenJDK.kt, src/main/kotlin/com/atlassian/performance/tools/infrastructure/api/jvm/OpenJDK11.kt, src/main/kotlin/com/atlassian/performance/tools/infrastructure/api/jvm/OracleJDK.kt, src/main/kotlin/com/atlassian/performance/tools/infrastructure/api/jvm/VersionedJavaDevelopmentKit.kt, src/test/kotlin/com/atlassian/performance/tools/infrastructure/api/jvm/JstatSupport.kt
To be able to run performance tests for OpenJDK 11 we have to set GC params based on Java version.
=> JPERF-408 Set GC params based on Java version

.travis.yml
https://travis-ci.com/atlassian/infrastructure/jobs/192189041/config failed and did not notify on Slack.
I used http://www.yamllint.com/ to parse the YAML and it turns out the current multiline syntax adds spaces on every new line. I used the same linter to check the fixed version.
=> Fix chopped multiline in Travis YAML

CHANGELOG.md, src/main/kotlin/com/atlassian/performance/tools/infrastructure/api/database/LicenseOverridingMysql.kt, src/main/kotlin/com/atlassian/performance/tools/infrastructure/database/SshMysqlClient.kt, src/main/kotlin/com/atlassian/performance/tools/infrastructure/database/SshSqlClient.kt, src/test/kotlin/com/atlassian/performance/tools/infrastructure/api/database/LicenseOverridingMysqlTest.kt, src/test/kotlin/com/atlassian/performance/tools/infrastructure/database/SshMysqlClientTest.kt, src/test/kotlin/com/atlassian/performance/tools/infrastructure/mock/RememberinSshConnection.kt
This effectively pulls in improvements first implemented in 
- https://github.com/atlassian/jira-hardware-exploration/blob/master/src/test/kotlin/com/atlassian/performance/tools/lib/SshMysqlClient.kt
- https://github.com/atlassian/jira-hardware-exploration/blob/c3af5a3254bd71f77febf8e6d0d747fa88880bc1/src/test/kotlin/com/atlassian/performance/tools/lib/LicenseOverridingDatabase.kt
=> JPERF-523 deprecate the use of strings to hold and transfer jira licenses

CHANGELOG.md, src/main/kotlin/com/atlassian/performance/tools/infrastructure/api/browser/chromium/CustomChromium.kt
Added new parametrized CustomChromium allowing to use specified URIs for browser and driver
=> Added new parametrized CustomChromium

CHANGELOG.md
Fix the misplaced changelog entry.
=> Mark 4.15.0 release

CHANGELOG.md
Artifacts: https://packages.atlassian.com/maven-public/com/atlassian/performance/tools/infrastructure/4.15.1/
=> Mark 4.15.1 release.

CHANGELOG.md
Artifacts: https://packages.atlassian.com/maven-public/com/atlassian/performance/tools/infrastructure/4.17.0/
4.16.1 shouldn't have been released as recent changes demand a minor release.
=> Mark 4.17.0 release

CHANGELOG.md, build.gradle.kts, gradle/dependency-locks/apiDependenciesMetadata.lockfile, gradle/dependency-locks/compileClasspath.lockfile, gradle/dependency-locks/default.lockfile, gradle/dependency-locks/implementationDependenciesMetadata.lockfile, gradle/dependency-locks/runtimeClasspath.lockfile, gradle/dependency-locks/testApiDependenciesMetadata.lockfile, gradle/dependency-locks/testCompile.lockfile, gradle/dependency-locks/testCompileClasspath.lockfile, gradle/dependency-locks/testImplementationDependenciesMetadata.lockfile, gradle/dependency-locks/testRuntime.lockfile, gradle/dependency-locks/testRuntimeClasspath.lockfile, src/main/kotlin/com/atlassian/performance/tools/infrastructure/api/os/Ubuntu.kt, src/test/kotlin/com/atlassian/performance/tools/infrastructure/api/browser/chromium/Chromium69IT.kt, src/test/kotlin/com/atlassian/performance/tools/infrastructure/api/jvm/ThreadDumpIT.kt, src/test/kotlin/com/atlassian/performance/tools/infrastructure/browser/SshChromium.kt
There's still 7 retries of `Ubuntu` install.
Exponential backoff with base 5 seconds and exponent of two meant that the 7th attempt took 640 seconds.
Sum of all 7 attempts took 1270 seconds max.
Now the backoff is 5 seconds + jitter between 0 and 10 seconds. Max of 15 seconds per attempt.
Sum of all 7 attempts now takes 105 seconds max.
=> JPERF-619: Reduce max `Ubuntu.install` backoff

CHANGELOG.md, src/main/kotlin/com/atlassian/performance/tools/infrastructure/Docker.kt
Docker.kt was using package that apt-get couldn't find `apt list -a docker` revealed that there is in fact that package, but only with specific version.
Bumping the version solved the problem.
=> JPERF-664 Use existing package for docker install.

CHANGELOG.md, src/main/kotlin/com/atlassian/performance/tools/infrastructure/HttpResource.kt
Fix errors, when running integration tests on Windows Subsystem for Linux:
```
java.lang.Exception: Error while executing lftp -c 'set net:timeout 15; set net:max-retries 10; pget -n 32 -c "https://product-downloads.atlassian.com/software/jira/downloads/atlassian-jira-software-7.2.0.tar.gz" -o test/atlassian-jira-software-7.2.0.tar.gz'. Exit status code SshResult(exitStatus=1, output=, errorOutput=pget: /software/jira/downloads/atlassian-jira-software-7.2.0.tar.gz: Fatal error: max-retries exceeded)
```
=> Fix tests on WSL

CHANGELOG.md, src/main/kotlin/com/atlassian/performance/tools/infrastructure/api/jira/start/JiraLaunchScript.kt, src/main/kotlin/com/atlassian/performance/tools/infrastructure/api/jira/start/JiraStart.kt, src/main/kotlin/com/atlassian/performance/tools/infrastructure/api/jira/start/StartedJira.kt, src/test/kotlin/com/atlassian/performance/tools/infrastructure/api/jira/install/JiraLaunchScriptIT.kt
=> Generalize Jira start API

CHANGELOG.md, src/main/kotlin/com/atlassian/performance/tools/infrastructure/ChromedriverInstaller.kt, src/main/kotlin/com/atlassian/performance/tools/infrastructure/api/browser/Chrome.kt
This is to avoid installing incompatible versions of ChromeDriver and Chrome. For example at the moment, latest ChromeDriver is v90 which requires Chrome v90 which hasn't been released yet.
=> JPERF-732: Download ChromeDriver version that matches installed Chrome version

CHANGELOG.md, src/main/kotlin/com/atlassian/performance/tools/infrastructure/dataset/ObsoleteHttpDatasetPackage.kt
The https://s3.eu-central-1.amazonaws.com/jira-soke-tests-eu/ S3 bucket - which must not be used anymore - was only referenced when com.atlassian.performance.tools.infrastructure.api.dataset.HttpDatasetPackage deprecated three-parameter secondary constructor was used - resulting in ObsoleteHttpDatasetPackage instance created. But the download() operation for such-way constructed HttpDatasetPackage would fail anyways due to missing file in the deprecated jira-soke-tests-eu bucket. Therefore, I'm replacing the download() method at ObsoleteHttpDatasetPackage with throw UnsupportedOperationException implementation.
=> PERF-750: remove reference to jira-soke-tests-eu-s3 bucket

.github/workflows/ci.yml
The release CI in the current form requires up-to-date credentials stored in the GitHub's secrets feature of the repository. Tokens are generated for limited amount of time and need to be updated manually. This requires knowledge maintenance and is doomed to fail at some point.
We are using the mentioned credentials (token) in `axion-release` gradle plugin. This plugin is dependency of `gradle-release` gradle plugin developed by us. It is used to create git tags of releases.
With `axion-release` it's possible to reuse github automated mechanisms to authenticate git client operations. The way to do that is documented in https://axion-release-plugin.readthedocs.io/en/latest/configuration/ci_servers/#github-actions
In order to make the `github.token` work for git client mutable operations …
=> JPERF-902: Apply axion-release plugin's instructions to CI config

CHANGELOG.md, src/main/kotlin/com/atlassian/performance/tools/infrastructure/HttpResource.kt
It fixes running downloads on github actions where it previously failed with errors like:
`Error while executing lftp -c 'set net:timeout 15; set net:max-retries 50; pget -n 32 -c "https://product-downloads.atlassian.com/software/jira/downloads/atlassian-jira-software-7.13.0.tar.gz" -o ./atlassian-jira-software-7.13.0.tar.gz'. Exit status code SshResult(exitStatus=1, output=, errorOutput=pget: /software/jira/downloads/atlassian-jira-software-7.13.0.tar.gz: Cannot assign requested address`
=> JPERF-969 Prefer IPv4 before starting download of http resource

CHANGELOG.md, src/main/kotlin/com/atlassian/performance/tools/infrastructure/api/database/MinimalMySqlDatabase.kt, src/main/kotlin/com/atlassian/performance/tools/infrastructure/api/database/MySqlDatabase.kt, src/main/kotlin/com/atlassian/performance/tools/infrastructure/api/jira/MinimalMySqlJiraHome.kt, src/main/kotlin/com/atlassian/performance/tools/infrastructure/database/MySql.kt, src/main/resources/mysql-dbconfig.xml, src/test/kotlin/com/atlassian/performance/tools/infrastructure/api/database/MinimalMySqlDatabaseIT.kt, src/test/kotlin/com/atlassian/performance/tools/infrastructure/api/jira/MinimalMySqlJiraHomeTest.kt
New MySQL database can't be initialized with `--skip-grant-tables` and we need to add this flag for existing datasets
to recover from lack of GRANTs in most of those.
We don't need to update Jira's baseurl in new database, as it's set during Jira setup in web GUI.
New `MinimalMysqlDatabaseIT` adds around 2 min test time on my machine.
Mutating the code by removing `GRANT` from `MinimalMysqlDatabase` breaks the test.
New `MinimalMysqlJiraHomeTest` adds around 30 ms test time on my machine.
Currently `aws-infrastructure` module is not compatile with new API. An ability to skip Jira upgrade waiting is needed.
Draft can be found under https://github.com/atlassian/aws-infrastructure/pull/154
We are intentionally not cleaning up created temp dirs, as team believes it's unnecessary.
We are …
=> JPERF-996: Allow minimal MySQL setup

src/test/kotlin/com/atlassian/performance/tools/infrastructure/api/jvm/JstatSupport.kt
Previously 5 builds out of 7 failed. With the fix 5 builds in a row passed, however, there's still another test (MySqlDatabaseIT#shouldStartMysql) that is failing.
=> JPERF-1103 Give more time to Jstat.

CHANGELOG.md, src/main/kotlin/com/atlassian/performance/tools/infrastructure/api/profiler/AsyncProfiler.kt
Fix errors like:
```
Caused by: java.lang.Exception: SSH command exceeded timeout PT30S by PT2.861S
at com.atlassian.performance.tools.ssh.WaitingCommand.waitForCompletion(WaitingCommand.kt:43) ~[ssh-2.4.3.jar:?]
at com.atlassian.performance.tools.ssh.WaitingCommand.waitForResult(WaitingCommand.kt:21) ~[ssh-2.4.3.jar:?]
at com.atlassian.performance.tools.ssh.SshjConnection.safeExecute(SshjConnection.kt:63) ~[ssh-2.4.3.jar:?]
at com.atlassian.performance.tools.ssh.SshjConnection.safeExecute(SshjConnection.kt:52) ~[ssh-2.4.3.jar:?]
at com.atlassian.performance.tools.ssh.SshjConnection.execute(SshjConnection.kt:33) ~[ssh-2.4.3.jar:?]
at com.atlassian.performance.tools.ssh.api.SshConnection.execute(SshConnection.kt:27) ~[ssh-2.4.3.jar:?]
at …
```
=> JPERF-1081: Extend `AsyncProfiler` `stop` timeout

CHANGELOG.md, build.gradle.kts, gradle/dependency-locks/apiDependenciesMetadata.lockfile, gradle/dependency-locks/compileClasspath.lockfile, gradle/dependency-locks/default.lockfile, gradle/dependency-locks/implementationDependenciesMetadata.lockfile, gradle/dependency-locks/runtimeClasspath.lockfile, gradle/dependency-locks/testApiDependenciesMetadata.lockfile, gradle/dependency-locks/testCompile.lockfile, gradle/dependency-locks/testCompileClasspath.lockfile, gradle/dependency-locks/testImplementationDependenciesMetadata.lockfile, gradle/dependency-locks/testRuntime.lockfile, gradle/dependency-locks/testRuntimeClasspath.lockfile, src/main/kotlin/com/atlassian/performance/tools/infrastructure/ChromeForTesting.kt, src/main/kotlin/com/atlassian/performance/tools/infrastructure/ChromedriverInstaller.kt, src/main/kotlin/com/atlassian/performance/tools/infrastructure/api/browser/Chrome.kt, src/test/kotlin/com/atlassian/performance/tools/infrastructure/api/browser/ChromeIT.kt, src/test/kotlin/com/atlassian/performance/tools/infrastructure/browser/SshChromium.kt
With ChromeDriver version 115 the maintainers are no longer updating old registry and download infrastructure of ChromeDriver artifacts.
Our tests started to use Chrome 115, but the endpoints we were using didn't report compatible ChromeDriver version, so our code started to fail. See [JPERF-1217].
The new API is based on JSON artifacts available though googlechromelabs.github.io.
See: https://groups.google.com/g/chromedriver-users/c/clpipqvOGjE/m/5NxzS_SRAgAJ
[JPERF-1217]: https://ecosystem.atlassian.net/browse/JPERF-1217
=> JPERF-1217: Adapt to new ChromeDriver release

CHANGELOG.md, src/main/kotlin/com/atlassian/performance/tools/infrastructure/api/profiler/AsyncProfiler.kt, src/main/kotlin/com/atlassian/performance/tools/infrastructure/api/profiler/WallClockProfiler.kt, src/test/kotlin/com/atlassian/performance/tools/infrastructure/api/profiler/AsyncProfilerIT.kt
Since the bump, it's not SVG anymore.
=> Fix flamegraph file extension

CHANGELOG.md, src/main/kotlin/com/atlassian/performance/tools/infrastructure/api/os/Ubuntu.kt, src/main/kotlin/com/atlassian/performance/tools/infrastructure/api/profiler/AsyncProfiler.kt
https://packages.atlassian.com/maven-central/com/atlassian/performance/tools/infrastructure/4.28.0/
Also mark `@since` for 4.27.0.
=> Mark 4.28.0

CHANGELOG.md, src/main/kotlin/com/atlassian/performance/tools/infrastructure/api/jvm/EnabledJvmDebug.kt
It was impossible to connect from outside the host. Only localhost was allowed
It's possible to connect from any host (if firewall allows to)
=> DCPERF-423 Fix access to debugger
